apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: configservice-container
  strategy: {}
  template:
    metadata:
      labels:
        run: configservice-container
    spec:
      containers:
        - image: kastnerfabian/stock-ml-config
          imagePullPolicy: Always
          name: configservice
          resources: {}
          ports:
            - containerPort: 5000
      restartPolicy: Always
status: {}
